import { type NextPage } from "next";
import Head from "next/head";
import Link from "next/link";
import Upload from "./upload";

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen flex-col items-center justify-center">
        <div className="container flex flex-col items-center justify-center gap-12 px-4 py-16 ">
          <h1>Hello</h1>
          <Upload />
        </div>
      </main>
    </>
  );
};

export default Home;
