import { type NextPage } from "next";
import { signIn } from "next-auth/react";
import Head from "next/head";
import Link from "next/link";
import LoginButton from "~/components/loginbtn";
import Navbar from "~/components/navbar";
import { useSession } from "next-auth/react";
import Test from "~/components/test";

const Home: NextPage = () => {
  const { data: session } = useSession();
  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar />
      <div className="flex h-screen flex-col items-center">
        <LoginButton />
        <Test />
      </div>
    </>
  );
};

export default Home;
